### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tigerxy**
Some changes for the formular to add events.

### CODE REVIEW

**Comment by dszymczuk** [comment]
Thank you, but I will check you code and apply manually to my code.
I have another solution for languages :)

**Comment by tigerxy** [comment]
Why you doesn't develop direct with Github? It would be easier to help you with coding. :grimacing:

**Comment by dszymczuk** [comment]
Ok. 
I need time to look your solution :) Thank you for help in develop. 

New time, please make more, bit smaller pull request :) It will be easier to code review and faster make PR .

**Comment by tigerxy** [comment]
I have tried it to make smaller, but I not so familar with Git right now.

**Comment by dszymczuk** [comment]
I will make pull request and I will test your code and I will change some fragments :)

**Comment by dszymczuk** [comment]
I have to manually merge because datepicker has another lang than calendar (moment.js) .
If you have set "de" - it works. But if you will set "en-gb" - it won't work, because in mment.js is "en-gb" but in datepicker is "en-GB" .
I'm working on new version with new feature :)

**Pull request merged**
